name: sehool
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^1.1.2
  bloc: ^6.1.1
  cached_network_image: ^2.5.0
  carousel_slider: ^2.3.1
  chewie: ^0.12.1+1
  dio: ^3.0.10
  division: ^0.8.8
  dropdown_search: ^0.4.8
  enum_to_string: ^1.0.14
  file_picker: ^2.1.6
  flash: ^1.3.1
  fluentui_system_icons: ^1.1.91
  flutter_bloc: ^6.1.1
  flutter_phone_direct_caller: ^1.0.1
  flutter_rating_bar: ^3.2.0+1
  flutter_staggered_grid_view: ^0.3.4
  flutter_svg: null
  font_awesome_flutter: ^8.11.0
  freezed_annotation: ^0.12.0
  geolocator: ^6.1.14
  get_it: ^5.0.4
  google_fonts: ^1.1.1
  google_maps_flutter: ^1.1.1
  hive_flutter: ^0.3.1
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+21
  injectable: ^1.0.7
  intl: ^0.17.0
  json_annotation: ^3.1.1
  loading_overlay: ^0.2.1
  onesignal_flutter: ^2.6.2
  package_info: ^0.4.3+2
  pretty_dio_logger: ^1.1.1
  quiver: ^3.0.0
  sailor: ^0.7.1
  simple_animations: ^2.5.0
  supercharged: ^1.12.0
  transformer_page_view: ^0.1.6
  url_launcher: ^5.7.10
  validators: ^2.0.1
  video_player: ^1.0.1
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  # integration_test:
  #   sdk: flutter
  build_runner: null
  freezed: ^0.12.6
  hive_generator: ^0.8.2
  injectable_generator: ^1.0.7
  json_serializable: ^3.5.1
  lint: null

# dependency_overrides:
#   intl: ^0.17.0-nullsafety.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  localizely:
    project_id: 37475a29-9c93-4002-811f-4e1b191236bb
